configs:
-   active_set: default
    infiles:
        default:
        -   /home/marten/.config/i3/config.base
        test:
        -   /home/marten/.config/i3/config.base.test
    name: i3
    outfile: /home/marten/.config/i3/config
-   active_set: default
    infiles:
        default:
        -   /home/marten/.config/alacritty/alacritty.base.yml
    name: alacritty
    outfile: /home/marten/.config/alacritty/alacritty.yml
substitution:
    basepath: /home/marten/src/rtk/themes/
    default: true
    source: dracula.yaml
