configs:
-   name: i3
    infiles:
        default:
        -   /home/marten/.config/i3/config.base
        test: []
    outfile: /home/marten/.config/i3/config
    active_set: default
-   name: alacritty
    infiles:
        default:
        -   /home/marten/.config/alacritty/alacritty.base.yml
    outfile: /home/marten/.config/alacritty/alacritty.yml
    active_set: default
substitution:
    basepath: /home/marten/src/rtk/themes/
    default: true
    source: dracula.yaml
